sudo: false
dist: xenial

language: python

python:
  - '2.7'
  - '3.6'

addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-latex-extra
      - dvipng

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then export PYTHON_VERSION=2; wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O $HOME/miniconda2.sh; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then export PYTHON_VERSION=3; wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda3.sh; fi
  - chmod +x $HOME/miniconda${PYTHON_VERSION}.sh
  - "$HOME/miniconda${PYTHON_VERSION}.sh -b;"
  - export PATH=/home/travis/miniconda${PYTHON_VERSION}/bin:$PATH
#  - conda update --yes conda

install:
  - conda install --yes python=${TRAVIS_PYTHON_VERSION}
  - conda install --yes -c conda-forge libcxx
  - conda install --yes -c conda-forge mpich petsc4py mpi4py pyfftw
  - conda install --yes pip numpy scipy matplotlib nose pep8 coverage sympy dill numba sphinx
  - conda install --yes -c conda-forge fenics
  - conda list
  - pip install travis-sphinx

script:
  - "./docs/update_apidocs.sh"
  - which nosetests
#  - export OMPI_MCA_btl_vader_single_copy_mechanism=none
  - export PYTHONPATH=$PYTHONPATH:../../..
  - nosetests -v --with-coverage --cover-erase --cover-inclusive --cover-package=pySDC/core,pySDC/implementations,pySDC/helpers,pySDC/tutorial,pySDC/projects --cover-html --cover-html-dir=doc/build/test_coverage pySDC/tests
  - if [[ $PYTHON_VERSION == 3 ]]; then travis-sphinx build; fi

after_success:
  - if [[ $PYTHON_VERSION == 3 ]]; then travis-sphinx deploy; fi

deploy:
  - provider: pypi
    edge:
      branch: jc-pypi
    user: pancetta
    password:
      secure: id5Pg/GL/YdXFmbi5h4xLmmyv/0L8lj9Rlr7lFJBrHrmkHIlu78NgO+LnQsGvhSrZqdDvZwRzFFCKRLiDugp07rzfwM41ROPrcgwnSRuqnzG2sUecNulNGHHoqej/z8nG5Ss8k2+viMqpOjhhZoY3LR0D1nFxRzu3HtHs0MKpRc=
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"