sudo: false
dist: xenial

language: python

python:
  - '2.7'
  - '3.6'

env:
  matrix:
    - TEST = test_.*py
    - TEST = test_tutorials/test_step_1.py
    - TEST = test_tutorials/test_step_2.py
    - TEST = test_tutorials/test_step_3.py
    - TEST = test_tutorials/test_step_4.py
    - TEST = test_tutorials/test_step_5.py
    - TEST = test_tutorials/test_step_6.py
    - TEST = test_tutorials/test_step_7.py
    - TEST = test_projects/test_asympconv
    - TEST = test_projects/test_fwsw
    - TEST = test_projects/test_hamiltonian
    - TEST = test_projects/test_matrixPFASST
    - TEST = test_projects/test_node_failure
    - TEST = test_projects/test_parallelSDC
    - TEST = test_projects/test_RDC
    - TEST = test_projects/test_SDC_showdown
    - TEST = test_projects/test_TOMS

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then export PYTHON_VERSION=2; wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O $HOME/miniconda2.sh; fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then export PYTHON_VERSION=3; wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda3.sh; fi
  - chmod +x $HOME/miniconda${PYTHON_VERSION}.sh
  - "$HOME/miniconda${PYTHON_VERSION}.sh -b;"
  - export PATH=/home/travis/miniconda${PYTHON_VERSION}/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes python=${TRAVIS_PYTHON_VERSION}
  - conda install --yes -c conda-forge mpich petsc4py mpi4py pyfftw
  - conda install --yes pip numpy scipy matplotlib nose pep8 coverage sympy dill numba sphinx
  - conda list
  - pip install travis-sphinx
  - sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra dvipng

script:
  - "./docs/update_apidocs.sh"
  - which nosetests
  - export OMPI_MCA_btl_vader_single_copy_mechanism=none
  - export PYTHONPATH=$PYTHONPATH:../../..
  - nosetests -v --with-coverage --cover-erase --cover-inclusive --cover-package=pySDC/core,pySDC/implementations,pySDC/helpers,pySDC/tutorial,pySDC/projects --cover-html --cover-html-dir=doc/build/test_coverage pySDC/tests/$TEST
  - if [[ $PYTHON_VERSION == 3 ]]; then travis-sphinx build; fi

after_success:
  - if [[ $PYTHON_VERSION == 3 ]]; then travis-sphinx deploy; fi

deploy:
  - provider: pypi
    edge:
      branch: jc-pypi
    user: pancetta
    password:
      secure: id5Pg/GL/YdXFmbi5h4xLmmyv/0L8lj9Rlr7lFJBrHrmkHIlu78NgO+LnQsGvhSrZqdDvZwRzFFCKRLiDugp07rzfwM41ROPrcgwnSRuqnzG2sUecNulNGHHoqej/z8nG5Ss8k2+viMqpOjhhZoY3LR0D1nFxRzu3HtHs0MKpRc=
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"